---
- hosts: Aphase1
  gather_facts: false
  become: yes
  vars:
    users:
      - name: {{ secrets_group.phase2_ansible_user.name }}
        pass: {{ getSaltedPassword(secrets_group.phase2_ansible_user.password) }}
        ssh_key: {{ secrets_group.phase2_ansible_user.ssh_key }}
        ssh_path: {{ secrets_group.phase2_ansible_user.ssh_path }}
    system_vars:
      ssh_port: {{ secrets_group.phase2_ansible_user.ssh_port }}
      packages:
  {% for pkg in secrets_group.packages %}
        - {{ pkg }}
  {% endfor %}
  tasks:
{% raw %}
# add user, make it admin
    - name: "new user"
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        groups: # Empty by default, here we give it some groups
         - sudo
        state: present
      with_items: "{{ users }}"
# give the user an ssh key
    - name: "user ssh key"
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', item.ssh_key) }}"
      with_items: "{{ users }}"
      when: not ansible_check_mode
# change hostname
    - name: Change the hostname to our standard
      hostname:
        name: "{{ inventory_hostname }}"
# install packages
    - name: "install base packages"
      apt: name={{ item }} state=present
      with_items: "{{ system_vars.packages }}"
      when: not ansible_check_mode
# copy a templated config file for sshd, restart it
    - name: "copy config_sshd file with owner and permissions"
      copy:
        # takes it from ./manifests anyway
        src: config_sshd_Aphase1
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
    - name: "restart sshd"
      service:
        name: sshd
        state: restarted
{% endraw %}
