---
groups:
  phase1:
    hosts:
    - test01
  raspbian:
    hosts:
    - test01
hosts:
  test01:
    ansible_ssh_port: 22
    ansible_user:
      name: pi
      password: raspberry
    ip: 192.168.0.1
