version: '3.1'

services:
  backend:
    image: angelalonso/cns_datafeed_backend_armv6:v0.12
    ports: 
      - "81:8080"
    environment:
      DB_NAME_FILE: /run/secrets/db_feed_name 
      DB_USER_FILE: /run/secrets/db_feed_user
      DB_PASS_FILE: /run/secrets/db_feed_pass
      DB_PSQL_HOST: "db"
      DB_PSQL_PORT: "5432"
    secrets:
      - db_feed_user
      - db_feed_pass
      - db_feed_name
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 25M
secrets:
  db_feed_name:
    external: true
  db_feed_user: 
    external: true
  db_feed_pass:
    external: true
networks:
  default:
    external:
      name: grid

