version: '3'

services:
  fe:
    image: angelalonso/cns_datafeed_frontend_armv6:v0.10
    ports: 
      - "80:9000"
    environment:
      DB_NAME_FILE: /run/secrets/db_feed_name 
      DB_USER_FILE: /run/secrets/db_feed_user
      DB_PASS_FILE: /run/secrets/db_feed_pass
      DB_PSQL_HOST: "db"
      DB_PSQL_PORT: "5432"
      PORT: "9000"
      FILES_SOURCE: "https://homelab_backend.fonseca.de.com/files/"

    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 25M
secrets:
  db_feed_name:
    external: true
  db_feed_user: 
    external: true
  db_feed_pass:
    external: true
networks:
  default:
    external:
      name: grid
