version: '3.1'

services:
  db:
    image: arm32v6/postgres:11.4-alpine
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_DB_FILE: /run/secrets/pg_database
    secrets:
      - pg_password
      - pg_user
      - pg_database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.labels.type == db
      resources:
        limits:
          cpus: '0.1'
          memory: 25M
secrets:
  pg_user:
    external: true
  pg_password:
    external: true
  pg_database:
    external: true
volumes:
  db-data:
    driver: local
networks:
  default:
    external:
      name: grid

