version: '3'

services:
  frontend:
    image: angelalonso/homelab_frontend_armv6:0.06
    ports: 
      - "80:4480"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=4490
networks:
  default:
    external:
      name: grid
