version: '3'

services:
  fe:
    image: angelalonso/homelab_frontend_armv6:0.06
    ports: 
      - "80:4480"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=4490
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 25M
networks:
  default:
    external:
      name: grid
