--- 
tokyo: 
  ssh_port: 45045
  user: 
    aafmin: 
      ssh_key: aafmin.priv
      belongs_to_groups: 
      - admin
      - asd
  group:
  - asd
riga: 
  ssh_port: 21012
  user: 
    aafmin: 
      ssh_key: aafmin.priv
      belongs_to_groups: 
      - admin
      - asd
  group:
  - asd
