apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-client-db-init-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    server: 10.43.47.213
    path: /datafeed/init

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-client-db-init-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
