---
hosts:
  test01:
    hostgroups:
    - mailservers
    - wordpress
    - ubuntu
    ip: "192.168.0.1"
    ssh_user: test
    ssh_pass: testpass
    ssh_key: 
    users:
      admin:
        password: admintestpass
      nonadmin:
        password: nonadmintestpass
  test02:
    hostgroups:
    - ubuntu
    ip: "192.168.0.2"
    ssh_user: test2
    ssh_pass: testpass2
    ssh_key: 
    users:
      admin:
        password: admintestpass2
      nonadmin:
        password: nonadmintestpass2
