---
hosts:
  test01:
    hostgroups:
    - mailservers
    - wordpress
    - ubuntu
    ip: "192.168.0.1"
    ansible_ssh_user: test
    ansible_ssh_pass: testpass
  test02:
    hostgroups:
    - ubuntu
    ip: "192.168.0.2"
    ansible_ssh_user: test2
    ansible_ssh_pass: testpass2
groups:
  ubuntu:
    ssh_key: 
    users:
      admin:
        password: test
      nonadmin:
        password: nontest

