---
hosts:
  test01:
    ip: "192.168.0.1"
    ansible_user:
      name: test1
      password: testpass1
  test02:
    ip: "192.168.0.2"
    ansible_user:
      name: test2
      password: 'testpass2'
      ssh_key: /bla/bleh.pem
groups:
  ubuntu:
    hosts:
    - test01
    - test02
    ansible_user:
      admin:
        password: test
        ssh_key:
    other_users:
      nonadmin:
        password: nontest
        ssh_key:
