---
hosts:
  test01:
    ip: "192.168.0.1"
    ansible_user:
      name: test1
      password: testpass1
  test02:
    ip: "192.168.0.2"
    ansible_user:
      name: test2
# if there's an ssh_key, password will still be used to gain sudo
      password: 'testpass2'
      ssh_key: /bla/bleh.pem
groups:
  ubuntu:
    hosts:
    - test01
    - test02
    ssh_port: 2222
    packages:
      - python-apt
      - git
      - vim
    ansible_user:
      name: admin
      password: test
      ssh_key: "/home/admin/.ssh/admin.pub"
      ssh_path: "/home/admin/.ssh"
#   other_users:
  debian:
    hosts:
    ssh_port: 2222
    packages:
      - python-apt
      - git
      - vim
    ansible_user:
      name: admin
      password: test
      ssh_key: "/home/admin/.ssh/admin.pub"
      ssh_path: "/home/admin/.ssh"
#   other_users:
