apiVersion: v1
kind: Service
metadata:
  name: cns-db
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5432 
    protocol: TCP
    targetPort: 5432 
  selector:
    app: cns-db
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

