apiVersion: apps/v1
kind: Deployment
metadata:
  name: cns-fe
spec:
  selector:
    matchLabels:
      app: cns-fe
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cns-fe
    spec:
      containers:
      - name: cns-frontend
        image: angelalonso/cns_datafeed_frontend_armv6:v0.13
        ports:
        - containerPort: 80
        volumeMounts:
        # name must match the volume name below
          - name: cns-fe-secret-volume
            mountPath: /secrets
          - name: volume-cns
            mountPath: /cns
        envFrom:
          - configMapRef:
              name: cns-fe-config
      volumes:
        - name: cns-fe-secret-volume
          secret:
            secretName: cns-fe-secret
        - name: volume-cns
          persistentVolumeClaim:
            claimName: cns-fe-images-pvc

