apiVersion: apps/v1
kind: Deployment
metadata:
  name: cns-fe
spec:
  selector:
    matchLabels:
      app: cns-fe
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cns-fe
    spec:
      containers:
      - name: cns-frontend
        image: angelalonso/cns_datafeed_frontend_armv6:v0.13
        ports:
        - containerPort: 80

