apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cns_fe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cns_fe
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
        - containerPort: 80
