apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homelab-fe
  namespace: default
spec:
  rules:
    - host: homelab.fonseca.de.com
      http:
        paths:
          - path: /
            backend:
              serviceName: cns-fe
              servicePort: 80

