apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homelab
  namespace: default
spec:
  rules:
    - host: homelab.fonseca.de.com
      http:
        paths:
          - path: /
            backend:
              serviceName: cns_fe
              servicePort: 80

