apiVersion: v1
kind: PersistentVolume
metadata:
  name: cns-fe-images-pv
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/aafmin/datafeed-frontend/raw
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - tokyo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cns-fe-images-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
