apiVersion: v1                                                                                                                                                                                                     
kind: PersistentVolume
metadata:
  name: cns-images-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aafmin/datafeed-frontend/raw"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cns-images-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
