- gather_facts: no
  hosts: "*"
  become: yes
  tasks:

    # APT #

    - name: Apt upgrade
      apt:
        update_cache: yes
        upgrade: yes
      tags:
        - prod
        - do_always

    - name: Remove a list of packages
      ansible.builtin.apt:
        pkg:
        - python-configparser
        state: absent
      tags:
        - prod
        - do_once

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - libffi-dev 
        - libssl-dev
        - python3 
        - python3-pip 
        - python3-setuptools
        - rustc
        - software-properties-common
        - ufw
        - vim
        - virtualenv
      tags:
        - prod
        - do_once

    # SCRIPTS AND FILES #

    - name: Creates scripts directory
      file:
        path: /home/{{ user }}/scripts
        state: directory
      tags:
        - prod
        - do_once

    - name: Copy over script to blink LED
      ansible.builtin.template:
        src: ../files/led_blink.py
        dest: /home/{{ user }}/scripts/led_blink.py
      tags:
        - prod
        - do_once

