- gather_facts: no
  hosts: "*"
  become: yes
  tasks:

    - name: Template SSHD config
      ansible.builtin.template:
        src: ../templates/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
      tags:
        - prod
        - do_once

    - name: Template SSH authorized_keys
      ansible.builtin.template:
        src: ../templates/authorized_keys
        dest: "/home/{{ user }}/.ssh/authorized_keys"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      tags:
        - prod
        - do_once

    - name: Allow SSH port
      community.general.ufw:
        rule: allow
        port: "{{ ssh_port }}"
        proto: tcp
      tags:
        - prod
        - do_once

    - name: Deny everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
      tags:
        - prod
        - do_once

    - name: Deny Ports, prometheus
      community.general.ufw:
        rule: deny
        port: 9090
        proto: tcp
      tags:
        - prod
        - do_once

