- hosts: "*"
  become: yes
  tasks:

    - name: Allow SSH port
      community.general.ufw:
        rule: allow
        port: "{{ ssh_port }}"
        proto: tcp
      tags:
        - prod
        - do_once

    - name: Deny everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
      tags:
        - prod
        - do_once

