apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homelab-be
  namespace: default
spec:
  rules:
    - host: homelab-backend.fonseca.de.com
      http:
        paths:
          - path: /
            backend:
              serviceName: cns-be
              servicePort: 80

