---
- hosts: k3s
  gather_facts: false
  become: no
  tasks:
{% raw %}
# install k3s
    - name: Use iptables-legacy
      become: yes
      shell:  update-alternatives --set iptables /usr/sbin/iptables-legacy > /dev/null
      when: not ansible_check_mode
    - name: Use iptables-legacy, IPv6
      become: yes
      shell:  update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy > /dev/null 
      when: not ansible_check_mode
    - name: cmdline cgroups 
      become: yes
      replace:
        destfile: /boot/cmdline.txt
        regexp: "^console=serial0,115200 console=tty1 root=PARTUUID=6c586e13-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait$"
        replace: "console=serial0,115200 console=tty1 root=PARTUUID=6c586e13-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"
    - name: Execute the k3s installer
      #      shell: curl -sfL https://get.k3s.io | sh -
      become: yes
      shell:  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server --no-deploy traefik --cluster-cidr=192.168.0.0/17 --service-cidr=192.168.128.0/17' sh -s -
      when: not ansible_check_mode
    - name: Add k3s alias for our user
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        regexp: "^alias k3='sudo k3s kubectl '$"
        line: "alias k3='sudo k3s kubectl '"
        owner: '{{ ansible_user }}'
        state: present
        insertafter: EOF
        create: True

{% endraw %}
# prepare memory to run k3s
