---
- hosts: etchosts
  gather_facts: no
  become: yes
  vars:
    system_vars:
      hosts:
  {% for host, values in secrets.hosts.items() %}
        - {{ host }}:
          ip: {{ values.ip }}
  {% endfor %}
  tasks:
{% raw %}
    - name: Update /etc/hosts with new hostname
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: "^127.0.1.1\traspberrypi$"
        line: "127.0.1.1\t{{ inventory_hostname }}"
        state: present
{% endraw %}
