---
- hosts: k3s
  gather_facts: false
  become: no
  tasks:
{% raw %}
# install k3s
    - name: Use iptables-legacy
      become: yes
      shell:  update-alternatives --set iptables /usr/sbin/iptables-legacy > /dev/null
      when: not ansible_check_mode
    - name: Use iptables-legacy, IPv6
      become: yes
      shell:  update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy > /dev/null 
      when: not ansible_check_mode
    - name: Change GPU Mem to 16
      become: yes
      lineinfile:
        path: /boot/config.txt
        regexp: "^gpu_mem=.*"
        line: "gpu_mem=16"
        state: present
    # configure ufw to allow traffic within the cluster
    - name: Allow all machines in cluster access to all ports
      become: yes
      ufw:
        rule: allow
        comment: 'k8s cluster'
        src: '192.168.0.0/24'
      when: not ansible_check_mode
    - name: cmdline cgroups 
      become: yes
      replace:
        destfile: /boot/cmdline.txt
        regexp: "^console=serial0,115200 console=tty1 root=PARTUUID=6c586e13-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait$"
        replace: "console=serial0,115200 console=tty1 root=PARTUUID=6c586e13-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"
        #    - name: Execute the k3s installer
        #    #      shell: curl -sfL https://get.k3s.io | sh -
        #      become: yes
        #      shell: export INSTALL_K3S_SKIP_START=true && export INSTALL_K3S_VERSION='v1.0.1' && curl -sfL https://get.k3s.io | sh -s -
        #      when: not ansible_check_mode
    - name: Add k3s alias for our user
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        regexp: "^alias k3='sudo k3s kubectl '$"
        line: "alias k3='sudo k3s kubectl '"
        owner: '{{ ansible_user }}'
        state: present
        insertafter: EOF
        create: True
    - name: Add better alias for watch 
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        regexp: "^alias watch='watch '$"
        line: "alias watch='watch '"
        owner: '{{ ansible_user }}'
        state: present
        insertafter: EOF
        create: True
# install repos for application data
    - name: Clone CNS-FE repository into this machine
      git:
        repo: https://github.com/code-and-share/datafeed-frontend.git
        version: master
        dest: /home/aafmin/datafeed-frontend
      become: no
    - name: Clone CNS-BE repository into this machine
      git:
        repo: https://github.com/code-and-share/datafeed-backend.git
        version: master
        dest: /home/aafmin/datafeed-backend
      become: no


{% endraw %}
# prepare memory to run k3s
