---
- hosts: raspbian
  gather_facts: yes
  become: yes
  vars:
    users:
      - name: {{ secrets_group.ansible_user.name }}
        pass: {{ getSaltedPassword(secrets_group.ansible_user.password) }}
        ssh_key: {{ secrets_group.ansible_user.ssh_key }}
        ssh_path: {{ secrets_group.ansible_user.ssh_path }}
  {% if secrets_group.other_users is defined %}
  {% for name, values in secrets_group.other_users.items() %}
      - name: {{ name }}
        pass: {{ getSaltedPassword(values.password) }}
        ssh_key: {{ values.ssh_key }}
        ssh_path: {{ values.ssh_path }}
  {% endfor %}
  {% endif %}
    system_vars:
      ssh_port: {{ secrets_group.ssh_port }}
      packages:
  {% for pkg in secrets_group.packages %}
        - {{ pkg }}
  {% endfor %}
  tasks:
{% raw %}
# change hostname
    - name: "correct hostname"
      hostname:
        name: "{{ inventory_hostname }}"
        #    - name: "correct hostname 2"
        #      command: "/bin/hostname {{ hostvars.ansible_host }}" 
        #      become: yes
    - name: "add host name to /etc/hosts"
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: "127.0.0.1 {{ inventory_hostname }} localhost"
        state: present
# add user, make it admin
    - name: "new user"
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        groups: # Empty by default, here we give it some groups
         - sudo
        state: present
      with_items: "{{ users }}"
# give the user an ssh key
    - name: "user ssh key"
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', item.ssh_key) }}"
      with_items: "{{ users }}"
# remove pi user
    - name: "remove pi user"
      user:
       name: 'pi'
       state: absent
       remove: yes
# install packages
    - name: "install base packages"
      apt: name={{ item }} state=present
      with_items: "{{ system_vars.packages }}"
    - name: "copy sshd_config file with owner and permissions"
      copy:
        # ansible looks for src within manifests anyway
        src: sshd_config_raspbian 
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'
      notify: "restart sshd"
    - name: "restart sshd"
      service:
        name: sshd
        state: restarted
# configure ufw
    - name: Allow all access to SSH port
      ufw:
        rule: allow
        port: '{{ system_vars.ssh_port }}'
        comment: 'ssh access'
      with_items: "{{ system_vars }}"
      when: not ansible_check_mode
    - name: "deny everything and enable UFW"
      ufw:
        state: enabled
        policy: deny
      when: not ansible_check_mode
    - name: "restart machine"
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: True
    - name: Waiting for server to come back up
      local_action: wait_for host="{{ inventory_hostname }}" port="{{ system_vars.ssh_port }}" state=started
{% endraw %}
# expand root filesystem?
# python3 by default?
