---
- hosts: etchosts
  gather_facts: no
  become: yes
  vars:
    hostentries:
  {% for host, values in secrets.hosts.items() %}
      - { regexp: '{{ host }}$', line: '{{ values.ip }} {{ host }}' }
  {% endfor %}
  tasks:
{% raw %}
    - name: Add all known hosts to etchosts
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items: "{{ hostentries }}"
      when: not ansible_check_mode
    - name: Update /etc/hosts with new hostname
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ inventory_hostname }}$"
        line: "127.0.1.1\t{{ inventory_hostname }}"
{% endraw %}
