---
- hosts: Cetchosts
  gather_facts: no
  become: yes
  vars:
    hostentries:
  {% for host, values in secrets.hosts.items() %}
      - { regexp: '{{ host }}$', line: '{{ values.ip }} {{ host }}' }
  {% endfor %}
  tasks:
{% raw %}
    - name: Wait for the machine to be available
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: not ansible_check_mode
    - name: Add all known hosts to etchosts
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items: "{{ hostentries }}"
      when: not ansible_check_mode
    - name: Update /etc/hosts with new hostname, pt1, clean 127.0.1.1
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: '^\b127.0.1.1\b'
        line: ""
    - name: Update /etc/hosts with new hostname, pt2, move 127.0.1.1 after list of hosts in cluster. Sorry for the hack
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: '\b{{ inventory_hostname }}\b'
        line: "127.0.1.1\t{{ inventory_hostname }}"
{% endraw %}
