---
{% for group, values in secrets.groups.items() %}
- hosts: {{ group }}
  gather_facts: false
  become: yes
  vars:
    hostinfo:
    {% for hostname in values.hosts %}
      host: {{ hostname }}
    {% endfor %}
    users:
  {% for name, values in values.ansible_user.items() %}
      - name: {{ name }}
        pass: {{ getSaltedPassword(values.password) }}
        ssh_key: {{ values.ssh_key }}
  {% endfor %}
  {% for name, values in values.other_users.items() %}
      - name: {{ name }}
        pass: {{ getSaltedPassword(values.password) }}
        ssh_key: {{ values.ssh_key }}
  {% endfor %}
  tasks:
{% raw %}
    - name: "correct hostname"
      hostname:
        name: "{{ item.host }}"
      with_items: "{{ hostinfo }}"
    - name: "new user"
      user:
        name: "{{ item.name }}"
        password: "{{ item.pass }}"
        groups: # Empty by default, here we give it some groups
         - sudo
        state: present
      with_items: "{{ users }}"
    - name: "user ssh key"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', item.ssh_key) }}"
      with_items: "{{ users }}"
{% endraw %}
{% endfor %}
