---
- hosts: Braspbian
  gather_facts: yes
  become: yes
  vars:
    system_vars:
      # ATTENTION: you will need Aphase1 playbook too!
      ssh_port: {{ secrets.groups.Aphase1.phase2_ansible_user.ssh_port }}
      packages:
  {% for pkg in secrets_group.packages %}
        - {{ pkg }}
  {% endfor %}
  tasks:
{% raw %}
    - name: install base packages
      apt: name={{ item }} state=present
      with_items: '{{ system_vars.packages }}'
    - name: remove pi user
      user:
        name: pi
        state: absent
        remove: yes
    - name: Clone this repository into this machine
      git:
        repo: https://github.com/angelalonso/homelab.git
        version: master
        dest: /home/aafmin/homelab
      become: no

      #- name: Allow all access to SSH port
      #- ufw:
      #-   rule: allow
      #-   port: '{{ system_vars.ssh_port }}'
      #-   comment: 'ssh access'
      #- with_items: '{{ system_vars }}'
      #- when: not ansible_check_mode
    - #- name: Deny everything and enable UFW
      #- ufw:
      #-   state: enabled
      #-   policy: deny
      #- when: not ansible_check_mode
      #- name: Restart machine
      #- command: shutdown -r now 'Ansible updates triggered'
      #- async: 0
      #- poll: 0
      #- ignore_errors: True
    - name: Reboot
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: not ansible_check_mode
    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: not ansible_check_mode
{% endraw %}
# python3 by default?
