---
- hosts: Cmysql
  gather_facts: yes
  become: yes
  vars:
    system_vars:
      packages:
  {% for pkg in secrets_group.packages %}
        - {{ pkg }}
  {% endfor %}
    mysql_old_root_password: {{ secrets_group.mysql_old_root_password }}
    mysql_root_password: {{ secrets_group.mysql_root_password}}
    mysql_user: {{ secrets_group.mysql_user }}
    mysql_user_password: {{ secrets_group.mysql_user_password }}
    k3s_mysql_user: {{ secrets_group.k3s_mysql_user }}
    k3s_mysql_user_password: {{ secrets_group.k3s_mysql_user_password }}
  tasks:
{% raw %}
    - name: Allow all machines in cluster access to MySQL
      become: yes
      ufw:
        rule: allow
        port: 3306
        comment: 'MySQL to k8s cluster'
        src: '192.168.0.0/24'
      when: not ansible_check_mode
# TODO: /etc/mysql/mariadb.conf.d/50-server.cnf bind-adress
    - name: install base packages
      apt: name={{ item }} state=present
      with_items: '{{ system_vars.packages }}'
    - name: Set new user and password
      mysql_user: 
        name: "{{ mysql_user }}"
        host: '%'
        password: "{{ mysql_user_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: '*.*:ALL,GRANT'
        state: present
    - name: Create new database with name 'k3s'
      mysql_db:
        name: k3s
        state: present
    - name: Set k3s user and password
      mysql_user: 
        name: "{{ k3s_mysql_user }}"
        host: '%'
        password: "{{ k3s_mysql_user_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        priv: 'k3s.*:ALL,GRANT'
        state: present
{% endraw %}
