---
- hosts: raspbian
  gather_facts: yes
  become: yes
  vars:
    system_vars:
      packages:
  {% for pkg in secrets_group.packages %}
        - {{ pkg }}
  {% endfor %}
  tasks:
{% raw %}
# install packages
    - name: install base packages
      apt: name={{ item }} state=present
      with_items: '{{ system_vars.packages }}'
# remove pi
    - name: remove pi user
      user:
        name: pi
        state: absent
        remove: yes
# install this repo
    - name: Clone this repository into this machine
      git:
        repo: https://github.com/angelalonso/homelab.git
        version: master
        dest: /home/aafmin/homelab
      become: no

# configure ufw
    - name: Allow all access to SSH port
      ufw:
        rule: allow
        port: '{{ system_vars.ssh_port }}'
        comment: 'ssh access'
      with_items: '{{ system_vars }}'
      when: not ansible_check_mode
    - name: Deny everything and enable UFW
      ufw:
        state: enabled
        policy: deny
      when: not ansible_check_mode
    - name: Restart machine
      command: shutdown -r now 'Ansible updates triggered'
      async: 0
      poll: 0
      ignore_errors: True
{% endraw %}
# python3 by default?
